export interface Handle {
  id: string;
  name: string;
  platform: "Twitter" | "Facebook" | "Instagram" | "LinkedIn" | "YouTube";
  followers: number;
  posts: number;
  engagement: number;
  frequency: "Daily" | "Weekly" | "Bi-Weekly" | "Monthly";
}

export const mockHandles: Handle[] = [
  {
    id: "1",
    name: "@techguru",
    platform: "Twitter",
    followers: 50000,
    posts: 1000,
    engagement: 5000,
    frequency: "Daily",
  },
  {
    id: "2",
    name: "Fashion Trends",
    platform: "Instagram",
    followers: 100000,
    posts: 500,
    engagement: 10000,
    frequency: "Daily",
  },
  {
    id: "3",
    name: "Cooking Channel",
    platform: "YouTube",
    followers: 200000,
    posts: 300,
    engagement: 15000,
    frequency: "Weekly",
  },
  {
    id: "4",
    name: "Business Insights",
    platform: "LinkedIn",
    followers: 30000,
    posts: 200,
    engagement: 3000,
    frequency: "Weekly",
  },
  {
    id: "5",
    name: "Local News",
    platform: "Facebook",
    followers: 75000,
    posts: 1500,
    engagement: 7500,
    frequency: "Daily",
  },
  {
    id: "6",
    name: "@sciencenews",
    platform: "Twitter",
    followers: 80000,
    posts: 800,
    engagement: 6000,
    frequency: "Daily",
  },
  {
    id: "7",
    name: "Travel Experiences",
    platform: "Instagram",
    followers: 150000,
    posts: 600,
    engagement: 12000,
    frequency: "Weekly",
  },
  {
    id: "8",
    name: "Tech Reviews",
    platform: "YouTube",
    followers: 250000,
    posts: 400,
    engagement: 20000,
    frequency: "Bi-Weekly",
  },
  {
    id: "9",
    name: "Career Advice",
    platform: "LinkedIn",
    followers: 40000,
    posts: 250,
    engagement: 4000,
    frequency: "Weekly",
  },
  {
    id: "10",
    name: "Community Group",
    platform: "Facebook",
    followers: 60000,
    posts: 1200,
    engagement: 6000,
    frequency: "Daily",
  },
  {
    id: "11",
    name: "@politicsnow",
    platform: "Twitter",
    followers: 70000,
    posts: 1500,
    engagement: 7000,
    frequency: "Daily",
  },
  {
    id: "12",
    name: "Fitness Motivation",
    platform: "Instagram",
    followers: 120000,
    posts: 800,
    engagement: 9000,
    frequency: "Daily",
  },
  {
    id: "13",
    name: "DIY Projects",
    platform: "YouTube",
    followers: 180000,
    posts: 350,
    engagement: 14000,
    frequency: "Weekly",
  },
  {
    id: "14",
    name: "Startup Networking",
    platform: "LinkedIn",
    followers: 25000,
    posts: 180,
    engagement: 2500,
    frequency: "Weekly",
  },
  {
    id: "15",
    name: "Pet Lovers",
    platform: "Facebook",
    followers: 90000,
    posts: 1000,
    engagement: 9000,
    frequency: "Daily",
  },
  {
    id: "16",
    name: "@sportsupdates",
    platform: "Twitter",
    followers: 100000,
    posts: 2000,
    engagement: 10000,
    frequency: "Daily",
  },
  {
    id: "17",
    name: "Art Gallery",
    platform: "Instagram",
    followers: 80000,
    posts: 400,
    engagement: 8000,
    frequency: "Weekly",
  },
  {
    id: "18",
    name: "Educational Courses",
    platform: "YouTube",
    followers: 300000,
    posts: 500,
    engagement: 25000,
    frequency: "Bi-Weekly",
  },
  {
    id: "19",
    name: "Industry Trends",
    platform: "LinkedIn",
    followers: 35000,
    posts: 220,
    engagement: 3500,
    frequency: "Weekly",
  },
  {
    id: "20",
    name: "Local Events",
    platform: "Facebook",
    followers: 50000,
    posts: 800,
    engagement: 5000,
    frequency: "Weekly",
  },
];
